### ISSUE TITLE
Changed the way the folders bootstrap

### ISSUE THREAD

**Issue by candidosales** [emberjsbook/rocknrollcall-yeoman#3]
Commit to your CSS (page 49) still has the old ways of the Twitter Bootstrap. 

```
$icon-font-path: "../bower_components/bootstrap-sass/fonts/" !default;
@import "bootstrap-sass/lib/bootstrap";
```

The folders have changed to the Bootstrap:

```
$icon-font-path: "../bower_components/bootstrap-sass-oficial/vendor/assets/fonts/" !default;
@import "../bower_components/bootstrap-sass-oficial/vendor/assets/stylesheets/bootstrap";
```

Even putting the correct paths, generates an error grunt watch:

"Error: File to import not found or unreadable: ../bower_components/bootstrap-sass-oficial/vendor/assets/stylesheets/bootstrap.\A Load paths:\A /home/candidosg/rocknrollcall-yeoman/app/bower_components\A Compass::SpriteImporter\A /home/candidosg/rocknrollcall-yeoman/app/styles\A /home/candidosg/.rvm/gems/ruby-2.0.0-p247/gems/compass-core-1.0.1/stylesheets\A on line 2 of /home/candidosg/rocknrollcall-yeoman/app/styles/style.scss\A \A 1: $icon-font-path: \"../bower_components/bootstrap-sass-oficial/vendor/assets/fonts/\" !default;\A 2: @import \"../bower_components/bootstrap-sass-oficial/vendor/assets/stylesheets/bootstrap\";\A 3: @import url(http://fonts.googleapis.com/css?family=Pirata+One|Yanone+Kaffeesatz:400,700,300);\A 4: \A 5: $rockin: 'Pirata One', cursive;\A 6: $fancy: 'Yanone Kaffeesatz', sans-serif;\A 7: "

Can you help me?

**Comment by fkumro** [comment]
@candidosales There is a spelling mistake in the path. Change `oficial` to `official` and that should fix your error.

**Comment by pixelmint** [comment]
I feel like this is the same issue but I'm still not sure how to resolve it. 
Any help greatly appreciated

![screen shot 2015-01-19 at 11 48 31 am](https://cloud.githubusercontent.com/assets/10247244/5804122/6436f18a-9fd1-11e4-9b2a-abcb06ca436d.png)

**Comment by fkumro-employii** [comment]
```css
$icon-font-path: "../styles/fonts/" !default;
@import "../bower_components/bootstrap-sass-official/vendor/assets/stylesheets/b
ootstrap";
@import url(http://fonts.googleapis.com/css?family=Pirata+One|Yanone+Kaffeesatz:
400,700,300);
```

This is what ended up working for me.

**Comment by fkumro** [comment]
```css
$icon-font-path: "../styles/fonts/" !default;
@import "../bower_components/bootstrap-sass-official/vendor/assets/stylesheets/b
ootstrap";
@import url(http://fonts.googleapis.com/css?family=Pirata+One|Yanone+Kaffeesatz:
400,700,300);
```

This is what ended up working for me, in `app/styles/style.scss`.

**Comment by pixelmint** [comment]
Thanks, still seem to be having issues.
![screen shot 2015-01-19 at 11 59 32 am](https://cloud.githubusercontent.com/assets/10247244/5804290/ac8f136c-9fd2-11e4-995f-1de499ea4782.png)

Here's my file structure
![screen shot 2015-01-19 at 12 01 14 pm](https://cloud.githubusercontent.com/assets/10247244/5804310/e6e20704-9fd2-11e4-9d79-722fb3dd8c17.png)

**Comment by fkumro** [comment]
The scss file is looking for `bower_components/bootstrap-sass-official` but your file structure is  `bower_components/bootstrap-sass`. Remove the `-official` (example below) and let me know if this helps.

```css
$icon-font-path: "../styles/fonts/" !default;
@import "../bower_components/bootstrap-sass/vendor/assets/stylesheets/b
ootstrap";
@import url(http://fonts.googleapis.com/css?family=Pirata+One|Yanone+Kaffeesatz:
400,700,300);
```

**Comment by pixelmint** [comment]
Ah, I was going to the wrong folder. Thanks! Looks like some of the gliphi's aren't loading correctly although if I can just continue with the book, should be good.

**Comment by pixelmint** [comment]
![screen shot 2015-01-19 at 12 06 43 pm](https://cloud.githubusercontent.com/assets/10247244/5804439/e6d727de-9fd3-11e4-8299-6dae6fc84eb6.png)

**Comment by fkumro** [comment]
Good! Open up the console, network tab and see what the path is to the missing glyph (it will 404). Should help with debugging.

**Comment by pixelmint** [comment]
sounds good, i'll start looking into. Before I do, just a check, what is supposed to happen when I search? Currently it's binding to the title, the blue search button does nothing and activity brings up some strange orange red blocks.
![screen shot 2015-01-19 at 12 09 36 pm](https://cloud.githubusercontent.com/assets/10247244/5804475/480048a6-9fd4-11e4-9188-3443ef858db4.png)

**Comment by pixelmint** [comment]
Sorry for all the noob questions. 
It looks like the bootstrap files aren't loading from the correct directory. 
        <script src="bower_components/bootstrap-sass/js/affix.js"></script>
        <script src="bower_components/bootstrap-sass/js/alert.js"></script>
        <script src="bower_components/bootstrap-sass/js/dropdown.js"></script>
should be
        <script src="bower_components/bootstrap-sass/javascripts/bootstrap/affix.js"></script>
        <script src="bower_components/bootstrap-sass//javascripts/bootstrap/alert.js"></script>
        <script src="bower_components/bootstrap-sass//javascripts/bootstrap/dropdown.js"></script>

But where do I make these changes? Changing the index.html file does nothing.

**Comment by pixelmint** [comment]
fixed the link paths, but I'm still getting strange interface and these errors when clicking blue button:

 GET http://developer.echonest.com/api/v4/artist/search?api_key=Your%20API%20key…mages&bucket=hotttnesss&bucket=biographies&bucket=id:musicbrainz&name=test 
(index):1 XMLHttpRequest cannot load http://developer.echonest.com/api/v4/artist/search?api_key=Your%20API%20key…mages&bucket=hotttnesss&bucket=biographies&bucket=id:musicbrainz&name=test. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 400.
jquery.js:7845 GET http://developer.echonest.com/api/v4/song/search?api_key=Your%20API%20key&f…o_summary&bucket=song_hotttnesss&bucket=tracks&bucket=song_type&title=test 
(index):1 XMLHttpRequest cannot load http://developer.echonest.com/api/v4/song/search?api_key=Your%20API%20key&f…o_summary&bucket=song_hotttnesss&bucket=tracks&bucket=song_type&title=test. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 400.
ember.js:3285 generated -> controller:error Object {fullName: "controller:error"}
ember.js:3285 Intermediate-transitioned into 'error'

Think this book may be out of my league at the moment.  appreciate the help regardless.

**Comment by fkumro** [comment]
I see `Your API key` still in the URL for the API request. You need to register (for free) at echonest and replace `Your API key` with the API key they give you once you are registered. This may not 100% be the cause of your error but its a good place to start. Also your previous comment I don't follow as its blank where I assume images should be? No worries on questions!

**Comment by pixelmint** [comment]
Thanks everyone for you help. FYI, if anyone is stuck just trying to get the demo up and running before proceeding, it's probably best to just skip that step and proceed regardless. At least that was the bottle neck I was dealing with.

**Comment by rsareth** [comment]
I think It should fix the bower.json in order to specify the right version.

Reading this :
````
[...]
"bootstrap-sass": "~3.0.0",
[...]
````
means for me that the project depends on bootstrap-sass >= 3.0.0. Now, with the 'grunt serve' step, it downloads the version 3.1.1.0 that creates a completely new tree directory.

And I think it's the same problem with jQuery. In the book, I can read that it's about jquery-1.9.1 and I have right now the version 2.1.3.
